### ISSUE TITLE
plot recipes seem to ignore `q` value

### ISSUE THREAD

**Issue by klaff** [baggepinnen/MonteCarloMeasurements.jl#103]
```
### A Pluto.jl notebook ###
# v0.12.18

using Markdown
using InteractiveUtils

# ╔═╡ 18852bf0-59dc-11eb-39eb-ab7ac5af2611
begin
	import Pkg
	Pkg.activate(mktempdir())
	Pkg.add("Plots"); using Plots
	Pkg.add("Distributions"); using Distributions
	Pkg.add("MonteCarloMeasurements"); using MonteCarloMeasurements
end

# ╔═╡ a1913f60-59dc-11eb-3963-3dc9dda7fd30
x=0.0:0.1:10.0

# ╔═╡ 2a53e330-59dc-11eb-15fa-c3eb2c4e2fe4
f(x) = Particles(Normal(10.0, 1.0))+x^2*Particles(Normal(2.0, 1.0))

# ╔═╡ 854f5c60-59dc-11eb-1f44-edc1e16765c1
errorbarplot(x, f.(x), q=0.01)

# ╔═╡ cdd508e0-59dc-11eb-0e6b-4be48fbb47b3
errorbarplot(x, f.(x))

# ╔═╡ Cell order:
# ╠═854f5c60-59dc-11eb-1f44-edc1e16765c1
# ╠═cdd508e0-59dc-11eb-0e6b-4be48fbb47b3
# ╠═a1913f60-59dc-11eb-3963-3dc9dda7fd30
# ╠═2a53e330-59dc-11eb-15fa-c3eb2c4e2fe4
# ╠═18852bf0-59dc-11eb-39eb-ab7ac5af2611
```

**Comment by baggepinnen** [comment]
It's because `q` is not a keyword argument, it's positional.

**Comment by klaff** [comment]
Well, hey, would you look at that? It's working now!  OMG, I banged my head on that for 30 minutes - I went looking at the source code, couldn't see where it was going wrong but thought, maybe something changed in how Plots recipes worked?

I will say, this is not the first time that plots commands' happy acceptance of `keyword_argument_that_does_not_exist="anything"` has bit me, but usually it happens that I misspell the keyword and wonder why it doesn't seem to do anything.

I think I'll hit the Close button now. Thank you. Have a nice day.
