### ISSUE TITLE
How to make it work with NLsolve

### ISSUE THREAD

**Issue by zwwi** [baggepinnen/MonteCarloMeasurements.jl#106]
Thanks for the nice package!

My question is whether it is possible to make it work with `NLsolve` so as to get uncertainties of the roots of nonlinear equations.
For instance, taking the following equation
```julia
using NLsolve

function f!(F, x) 
    F[1] = (x[1]+3)*(x[2]^3-7)+18 #+ Particles(100)
    F[2] = sin(x[2]*exp(x[1])-1)
end

nlsolve(f!, [1, 0.0])
```
gives
```
Results of Nonlinear Solver Algorithm
 * Algorithm: Trust-region with dogleg and autoscaling
 * Starting Point: [1.0, 0.0]
 * Zero: [9.395026836849733e-12, 1.0000000000349933]
 * Inf-norm of residuals: 0.000000
 * Iterations: 8
 * Convergence: true
   * |x - x'| < 0.0e+00: false
   * |f(x)| < 1.0e-08: true
 * Function Calls (f): 7
 * Jacobian Calls (df/dx): 6
```
If including error in some inputs, e.g., uncommenting the `+ Particle(100)` in the above, I wonder how the errors can be propagated to the roots. A direct use gives `ArgumentError: Cannot convert a particle distribution to a float if not all particles are the same.` The only possible way I can think of is to solve for roots for all sampled parameters. Is there a more direct way?
Thank you!

**Comment by baggepinnen** [comment]
Hello, You have an interesting question here! I have a feeling it will be hard to support this in all generality. When you call `nlsolve(f!, [1, 0.0])` with a vector of `Float64`, NLSolve will assume that `Float64` is the number type to use. You could inform the solver that you instead want `Particles` by making sure the initial estimate is of the correct type, but even if you do, it's not clear to me how to express the solving algorithm in terms of atomic operations on `Particles´. The correct way to do this is probably to treat the solver function as a unit to propagate each individual particle through, but that will be hard to perform with the uncertain parameter encoded into the function itself. Had the solver accepted parameters to the function (like [NonlinearSolve.jl](https://github.com/JuliaComputing/NonlinearSolve.jl)), it might have worked out. 

Below is an example that "linearizes" the comparison operator to compare using the mean only. It produces something, but I honestly can't tell you if it makes sense or not.

```julia
using MonteCarloMeasurements, NLsolve

unsafe_comparisons(true)
p() = Particles(100)

const u = p()

function f!(F, x) 
    F[1] = (x[1]+3)*(x[2]^3-7)+18 + u
    F[2] = sin(x[2]*exp(x[1])-1)
end

x0 = [1 + 0p(), 0.0]
sol = nlsolve(f!,  x0)
sol.zero
```

**Comment by baggepinnen** [comment]
Here is an example using NonlinearSolve.jl

```julia
using MonteCarloMeasurements, NonlinearSolve
unsafe_comparisons(true)
p() = Particles(100)
const u = p()

function g(x, p) 
    [(x[1]+3)*(x[2]^3-7)+18 + p[]
    sin(x[2]*exp(x[1])-1)]
end

function outer_solve(x0, u)
    probN = NonlinearProblem{false}(g, x0, u)
    sol = solve(probN, NewtonRaphson(), tol = 1e-9)
end

@bymap outer_solve(x0, u)
```

**Comment by zwwi** [comment]
@baggepinnen  Thank you very much for the replies!

The question that I have in hand is to find roots of a complicated function in the complex plane. So I split the problem to two equations, being the real and imag parts, respectively.  
I tried both of your suggestions and still got the same  `Argument Error` with the function that I have at hand. It turns out to be due to the presence of logarithmic functions of complex variables. 
For instance, while `log(10+Particles(100))` works, `log(10+Particles(100)+0im)` does not. Could this be solved?

Also, it seems that NonlinearSolve cannot handle complex functions. 

Thank you again for this wonderful package.

**Comment by baggepinnen** [comment]
The `log` function for complex particles was added in the commit 278e713
Should you encounter more functions that does not work for complex particles, you might be able to solve the problem in a similar manner to how I fixed the issue for `log`.
