### ISSUE TITLE
Place package in JuliaPhysics?

### ISSUE THREAD

**Issue by crstnbr** [baggepinnen/MonteCarloMeasurements.jl#11]
As has been suggested by @giordano on [discourse](https://discourse.julialang.org/t/ann-montecarlomeasurements-jl/23021/4) already, maybe you want to have this package hosted under JuliaPhysics.

Although this package isn't strictly a physics package, Measurements.jl is part of JuliaPhysics so it might make sense to have them next to each other as they seem to serve the same purpose.

Feel free to close this issue if you prefer to leave it as a separate package.

**Comment by baggepinnen** [comment]
I do not have any experience with the JuliaPhysics organization and do not have a physics background myself. For now, I will keep the package here, in the future I might incorporate it into, e.g.,  [JuliaControl](https://github.com/JuliaControl), where most members are from my department. Control, estimation and identification were my motivations for developing the package so this org feels closer to me.
