### ISSUE TITLE
Type stable constructors for `Particles`

### ISSUE THREAD

**Issue by joachimbrand** [baggepinnen/MonteCarloMeasurements.jl#112]
Thanks for a great package! It's been very useful for my work already.

I noticed that some of the exposed constructors are not type stable. I found out through a downstream contamination issue in our code that uses MCM. My use case is that I need to propagate correlated errors through a ratio, for which I use `Particles(MvNormal)`.

Currently
```
julia> using Test

julia> @inferred 2±0.3
Particles{Float64, 2000}
 2.0 ± 0.3

julia> @inferred Particles()
Particles{Float64, 2000}
 -5.3290700000000004e-18 ± 1.0
```
are type-stable constructors, but 
```
julia> @inferred Particles(Normal(2, 0.3))
ERROR: return type Particles{Float64, 2000} does not match inferred return type Particles{Float64, _A} where _A
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] top-level scope
   @ none:1

julia> @inferred Particles(MvNormal([1.0, 2.0],[0.5 0.1;0.1 0.5]))
ERROR: return type Vector{Particles{Float64, 2000}} does not match inferred return type Vector{_A} where _A
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] top-level scope
   @ none:1
```
are not.

So, the `±` constructor is type stable, but it appears that there is no type stable constructor when supplying a custom (e.g. multivariate) distribution, even with the default number of particles. The problem appears to be that the number of particles is treated as run time information (even when it not needed to be).

I understand that the number of particles is a type parameter and thus any constructor that supplies this information at run time will be type-unstable. It should not be necessary for the default configuration, though (as seen with `±`). 

Also, would it be possible to expose type-stable constructors in the API? E.g. like
```
p = Particles{N}(d::Distribution)
```
This could be type stable in any code that uses literals for `N` or that propagates `N` as type information.

Finally, while I understand that `N` is type information for `StaticParticles`, is there a good reason that `N` is a type parameter for `Particles`? If `N` could be dropped as a type parameter, then the number of particles would just become run-time information like the length of any regular array, and type stability (and resulting downstream contamination) would not be an issue.

**Comment by baggepinnen** [comment]
Hello and thanks for the issue! I'll look into making all constructors type stable. It requires the `N` to enter the type domain in some way or another (I had hoped that constant propagation took care of this, but it doesn't). Having constructors like `Particles{N}` as you suggest appears to be a reasonable way to do this.

> Finally, while I understand that N is type information for StaticParticles, is there a good reason that N is a type parameter for Particles? 

The primary reason is to avoid code duplication, if the type signatures for all kinds of particles are the same, the code base can be kept much smaller.

**Comment by baggepinnen** [comment]
The constructor you mentioned above, and a few others, are now made type stable on master by means of introducing the typed constructors
```julia
$PT{T,N}(rng::AbstractRNG, d::Distribution)
$PT{T,N}(rng::AbstractRNG, d::MultivariateDistribution)
```
```julia
julia> @code_warntype Particles(MvNormal([1.0, 2.0],[0.5 0.1;0.1 0.5]))
Variables
  #self#::Type{Particles}
  d::FullNormal

Body::Vector{Particles{Float64, 2000}}
1 ─ %1 = Core.NamedTuple()::Core.Const(NamedTuple())
│   %2 = Base.pairs(%1)::Core.Const(Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}())
│   %3 = MonteCarloMeasurements.:(var"#Particles#43")(%2, #self#, d)::Vector{Particles{Float64, 2000}}
└──      return %3
```
I hope this resolves your type stability issues, if not, feel free to comment on this issue and I'll reopen it.

**Comment by joachimbrand** [comment]
Thanks, this is awesome! I'll try it out.
