### ISSUE TITLE
Base.length(x::Particles) = 1 for closer behavior to number

### ISSUE THREAD

**Issue by VEZY** [baggepinnen/MonteCarloMeasurements.jl#115]
I develop a package where there's a function testing the length of the argument, but the length of a Particles is the number of particles it has, not length 1, e.g.:

```julia
length(13.747 ± 1)
```
would return 2000.

I don't know if you share this thought but I would expect a Particles to behave like a number, so to have a length of 1 when using `length`, and maybe have another function to get the number of particles, e.g. `nparticles(x)`.

Now I could test whether the argument is a Particles, but then I would have to put MonteCarloMeasurements.jl as a dependency and I would prefer not to. I help the user use it though with a tutorial in the docs. 

At the moment I declared `Base.length(x::Particles) = 1` in the docs before using it in my function, and it appears not to break anything, but it is rather hacky if it's not in the package directly. 

Would you consider adding it to the package if this does not break anything?

**Comment by baggepinnen** [comment]
This behavior was changed in v1.0 that was released some day ago. Try to update the package and see if it behaves the way you want. ☺️

**Comment by VEZY** [comment]
Ha yes perfect! Sorry for not seeing that earlier, and thank you for answering this quick!
