### ISSUE TITLE
How to strip unit?

### ISSUE THREAD

**Issue by MartinOtter** [baggepinnen/MonteCarloMeasurements.jl#119]
```
module Test_ustrip

using MonteCarloMeasurements
using Unitful

a = (2 ∓ 0.2)u"s"
@show a

b = ustrip(a)
@show b

end
```

results in 

```
a = 1.9999999999999993 s ± 0.19972806084227734 s
b = 1.9999999999999993 s ± 0.19972806084227734 s
```

So the **unit is not stripped from `a`**.

How to strip the unit?

**Comment by MartinOtter** [comment]
Figured out one solution:

```
module Test_ustrip

using MonteCarloMeasurements
using Unitful

Unitful.ustrip(v::StaticParticles) = v / unit(v.particles[1])

a = (2 ∓ 0.2)u"s"
@show a
b = ustrip(a)
@show b
end
```

Resulting in 

```
a = 1.9999999999999993 s ± 0.19972806084227737 s
b = 2.0 ± 0.2
```

This is a bit strange. I would have expected to get exactly the same output, but with removed unit.

**Comment by MartinOtter** [comment]
A slightly better solution is:
```
Unitful.ustrip(v::AbstractParticles{T,N}) where {T,N} = v / unit(T)
```
Might be useful to add this definition to MonteCarloMeasurements.jl

**Comment by baggepinnen** [comment]
Thanks for the tip, it has been added :)

**Comment by MartinOtter** [comment]
This was quick!!!.

I recognized that it is not good enough, because there are other useful Unitful functions that do not work. A better solution is the following. Therefore, please remove the definition of ustrip(..) and instead provide the following two definitions of **unit** and of **upreferred** (ustrip is then automatically correctly working):

```
module Test_ustrip

using MonteCarloMeasurements
using Unitful

Unitful.unit(      v::AbstractParticles{T,N}) where {T,N} = unit(T)
Unitful.upreferred(v::AbstractParticles{T,N}) where {T,N} = uconvert(upreferred(unit(v)), v)

a = (200 ∓ 20)u"ms"
@show a
@show unit(a)

b = ustrip(a)
@show b

c = uconvert(u"s", a)
@show c

d1 = upreferred(a)
@show d1

d2 = ustrip(d1)
@show d2

end
```

results in the following output

```
a = 199.99999999999991 ms ± 19.972806084227745 ms
unit(a) = ms
b = 200.0 ± 20.0
c = 0.2000000000000001 s ± 0.01997280608422774 s
d1 = 0.2000000000000001 s ± 0.01997280608422774 s
d2 = 0.2 ± 0.02
```

**Comment by baggepinnen** [comment]
Closed by https://github.com/baggepinnen/MonteCarloMeasurements.jl/commit/8e6f2d73f1f22826eea1d89bf8b52c7b8bf3bc70
