### ISSUE TITLE
Differential Equations example gives error

### ISSUE THREAD

**Issue by brendandaisy** [baggepinnen/MonteCarloMeasurements.jl#120]
I'm getting an `ArgumentError: Cannot convert a particle distribution to a float if not all particles are the same` when running the Differential Equations example from the documentation. Using Measurements.jl works though.

I'm using MonteCarloMeasurements v1.0.6 and OrdinaryDiffEq v5.55.1 with Julia v1.7.1. Is this a known issue?

Thank you! This package seems really cool and I'm excited to use it.

**Comment by baggepinnen** [comment]
Hello and thanks for the report. I just tried the example and it runs fine here. The version of OrdinaryDiffEq you're running is slightly obsolete, Diff eq might have seen some changes in the time between your release and the one I'm running with `OrdinaryDiffEq v5.71.0`. If upgrading to the latest version of diff eq does not solve the problem, would you mind posting the full stack trace and error message and I'll see if I can spot a clue as to what might be wrong?
