### ISSUE TITLE
Fun use case: Variational inference

### ISSUE THREAD

**Issue by cscherrer** [baggepinnen/MonteCarloMeasurements.jl#23]
Your package is making it a lot easier to think about this sort of thing. I'd like to get this automated for Soss models, but for now it's hard-coded and seems to work pretty well:
https://gist.github.com/cscherrer/72062a3b9f264a328f00159d84a61b98

**Comment by baggepinnen** [comment]
Cool! I can't say I understand exactly what is going on.. You're maximizing the elbo of a linear regression model with normal priors on the coefficients using a VIS (?) algorithm?

**Comment by baggepinnen** [comment]
If you think this example can turn into something that others might find useful, we can add it to the examples  :)

**Comment by cscherrer** [comment]
Yeah I really need to write it up. It was just a crazy idea that ended up working surprisingly well, and being able to think and work in terms of particles made it all much easier. Pretty great abstraction once you get used to it :)

Hoping to get through a blog post today giving some details

**Comment by baggepinnen** [comment]
Wow yeah that sounds nice, I can link it from the Readme. It's great to hear that the package is general enough to work for something completely unforseen!

**Comment by baggepinnen** [comment]
I added a link to the blogpost in the readme :D
