### ISSUE TITLE
fft of Particles vector not working

### ISSUE THREAD

**Issue by arbenede** [baggepinnen/MonteCarloMeasurements.jl#25]
I am getting an error when I try to compute the fft of a vector of Particles. Are there any workarounds? In my specific case this is a 3 point fft, so I could just use an explicit formula, however I'd like to do this in the more general case as well at some point.

**Comment by baggepinnen** [comment]
Which `fft` function are you using? If you're using FFTW.jl, I believe this is calling out to a C library and can thus not be used with `Particle` types. One workaround is to use `@bymap` as detailed in the readme.
Examples
```julia
julia> Base.eps(::Type{Complex{Float64}}) = eps(Float64) # Seems to be needed for printing of complex uncertain values

julia> @bymap fft(a)
3-element Array{Particles{Complex{Float64},100},1}:
 0.302 - 0.0im ± 1.7   
 0.062 + 0.0137im ± 1.8
 0.062 - 0.0137im ± 1.8
```
I have not verified that this calculates the correct thing, so make sure to do that.

**Comment by baggepinnen** [comment]
Actually, having looked at it a bit more, it seems to produce weird results, where everything it put into the real part
```julia
julia> real(@bymap(fft(a)))
3-element Array{Particles{Complex{Float64},100},1}:
 0.302 - 0.0im ± 1.7   
 0.062 + 0.0137im ± 1.8
 0.062 - 0.0137im ± 1.8

julia> imag(@bymap(fft(a)))
3-element Array{Particles{Complex{Float64},100},1}:
 0.0 + 0.0im
 0.0 + 0.0im
 0.0 + 0.0im
```
I will look a bit close at it

**Comment by baggepinnen** [comment]
Okay, I think the problem is related to the representation of the results. One can imagine either
`Complex{Particles}` or `Particles{Complex}`, where the result is on the latter form, i.e., `Particles{Complex{Float64}}`. This type is probably cumbersome to work with, and perhaps it would be better to have the result on the other form. At the moment, manual conversion between these two forms is the only workaround. 

The same problem arises when particles are combined with dual numbers, e.g., from ForwardDiff.jl. You can see how I handle the conversion between these two formats here
https://github.com/baggepinnen/MonteCarloMeasurements.jl/blob/0dc5f0474f2f69b8025734e8c195e27aac496ab0/src/forwarddiff.jl#L8

**Comment by arbenede** [comment]
I tried to apply @bymap to solve a similar problems in a different section of my code, but I am getting an error. Here is a MWE:

```
x1 = Particles(80,Normal(30,5))
x2 = Particles(80,Normal(30,5))

y = im*(x1-x2)
z = @bymap exp(y)
```
gives
```
BoundsError: attempt to access ()
  at index [1]

Stacktrace:
 [1] getindex at .\tuple.jl:24 [inlined]
 [2] #s35#210(::Any, ::Any) at C:\Users\arbenede\.julia\packages\MonteCarloMeasurements\SyC4O\src\bymap.jl:24
 [3] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at .\boot.jl:522
 [4] top-level scope at C:\Users\arbenede\.julia\packages\MonteCarloMeasurements\SyC4O\src\bymap.jl:40
 [5] top-level scope at In[11]:1
```

**Comment by baggepinnen** [comment]
The problem with `exp` is documented in the readme, [here](https://github.com/baggepinnen/MonteCarloMeasurements.jl#%E2%84%82--%E2%84%82-functions). I will add `exp` to the supported methods, in the meantime, the solution is to define
```julia
Base.exp(z::Complex{<: AbstractParticles})  = ℂ2ℂ_function(exp, z)
```

**Comment by baggepinnen** [comment]
Support for `exp` and some other functions was added in ab9c75c9a9eb566a591910de0139d3828b91c1c4

**Comment by arbenede** [comment]
Thanks, I am closing the issue.

**Comment by baggepinnen** [comment]
I further added some support for in-place operations on complex particles to save some allocations, example:
```julia
julia> @btime exp($(y.*im))
  2.142 μs (3 allocations: 3.52 KiB)
0.606 ± 0.45 + 0.000115 ± 0.66*im

julia> @btime exp!($s, $(y.*im))
  2.083 μs (2 allocations: 1.75 KiB)
0.606 ± 0.45 + 0.000115 ± 0.66*im
```
