### ISSUE TITLE
Depend on RecursiveArrayTools?

### ISSUE THREAD

**Issue by cscherrer** [baggepinnen/MonteCarloMeasurements.jl#28]
I just discovered [RecursiveArrayTools](https://github.com/JuliaDiffEq/RecursiveArrayTools.jl), looks like it could be helpful for the kinds of manipulations you need to do for this library. Just pointing it out here in case you haven't come across it

**Comment by baggepinnen** [comment]
I'm aware of it, and even have a few commits contributions to it. It's not immediately clear to me where to make use of it in this package though, do you have any concrete examples where depending on this package might benefit us here?

**Comment by cscherrer** [comment]
Haha oops, I didn't realize you had contributed to it. You had mentioned needing to maneuver between array-of-particles and particles-of-arrays. I just learned of that package, and it seems to target that exact problem.

I'll close this now
