### ISSUE TITLE
0.3.5 release?

### ISSUE THREAD

**Issue by cscherrer** [baggepinnen/MonteCarloMeasurements.jl#30]
The `register_primitive` fix is a big help to me, so now I'm requiring `>=0.3.5` of your package. But that seems to cause problems for at least some users. Any chance you could tag a v0.3.5 release?

**Comment by baggepinnen** [comment]
I can't easily tag `0.3.5` due to some breaking changes introduced by the modification of plot functions. I am however preparing to release `0.4.0`

**Comment by baggepinnen** [comment]
New release https://github.com/baggepinnen/MonteCarloMeasurements.jl/releases/tag/v0.4.0
