### ISSUE TITLE
bymap on StaticParticles gives Particle 

### ISSUE THREAD

**Issue by MasonProtter** [baggepinnen/MonteCarloMeasurements.jl#46]
```julia
julia> using MonteCarloMeasurements

julia> p = StaticParticles(10)
SPart10(-4.441e-17 ± 0.989)

julia> h(x::Float64) = x + 1; p = StaticParticles(10)
SPart10(-8.882e-17 ± 0.989)

julia> @bymap h(p)
Part10(1.0 ± 0.989)
```
I would expect this to preserve in the input type.

**Comment by baggepinnen** [comment]
Unfortunately, the way it works internally uses mutation and thus its more efficient to use a regular vector. If your real use case is that simple, you can try `register_primitive` on `h`

**Comment by baggepinnen** [comment]
Maybe `ntuple` could replace map here

**Comment by baggepinnen** [comment]
I hope this is fixed now. There is now a function `bymap` that can be used instead of the macro. There should be no difference in performance, but if the function is used error messages will be a bit clearer.
