### ISSUE TITLE
Feature Request: Violin plots

### ISSUE THREAD

**Issue by MasonProtter** [baggepinnen/MonteCarloMeasurements.jl#48]
Violin plots (like those found in https://github.com/JuliaPlots/StatsPlots.jl) would be a nice way to visualize the distributions in a list of `Particle`s. It's currently a bit of a pain to use Particles with StatsPlots.violin, so it'd be nice if there was a way to smooth that here.

**Comment by baggepinnen** [comment]
Do you have a suggestion how this can be facilitated without a dependency on Statsplots?

**Comment by MasonProtter** [comment]
Probably we can just copy and paste from https://github.com/JuliaPlots/StatsPlots.jl/blob/master/src/violin.jl and make some tweaks. I'm not sure there's a better way. 

I'm not at all knowledgable about Plots.jl, but I'd be happy to at least give it a go sometime in the next couple weeks if nobody comes up with a better idea or beats me to it.

**Comment by baggepinnen** [comment]
Arviz
https://github.com/arviz-devs/ArviZ.jl
has support for MonteCarloMeasurements.jl and has a violin plot. I've never tested it, but maybe it works for you?

**Comment by baggepinnen** [comment]
I'm not sure what result you expect, but the following produces a nice plot that corresponds well to what I would expect
```julia
violin(Array([1 ± 2, 4 ± 1]))
```

**Comment by baggepinnen** [comment]
@MasonProtter feel free to close this issue if the snippet above solves your problem. If it doesn't, I'll have to know what behavior you would like to see. Thanks :)

**Comment by MasonProtter** [comment]
@baggepinnen Hm, that does seem to work well! The only thing I can't figure out right now is how to change the x axis, doing `violin(4:6, Array([1 ± 2, 3 ± 4, 1 ± 10]))` didn't do what I expected, but that might be more of a StatsPlots question than a MonteCarloMeasurements question

**Comment by baggepinnen** [comment]
Great! I believe the keyword you want is `xticks`
