### ISSUE TITLE
InexactError

### ISSUE THREAD

**Issue by alecloudenback** [baggepinnen/MonteCarloMeasurements.jl#50]
```julia 
@show a = Particles(1000,Bernoulli(0.1))
@show a * 2
@show a * 2.05
```
returns:
```
a = Particles(1000, Bernoulli(0.1)) = 0.094 ± 0.29
a * 2 = 0.188 ± 0.58
InexactError: Int64(2.05)
```

Intuitively I feel like the third line should work similar to the second, but maybe I don't understand some of the limitations of the particle technique used here?

**Comment by baggepinnen** [comment]
Each particle is an integer, `1/0` and when you multiply `a` with `2.05` it tries to fit the result into particles with the same numeric type as `a`, which currently does not work. There was a PR opened recently to make this work though https://github.com/baggepinnen/MonteCarloMeasurements.jl/pull/49 so it will soon work :)

**Comment by baggepinnen** [comment]
A workaround in the meantime might be to manually change the numeric type of `a`
```julia
2.05 * Particles(1.0a.particles)
```

**Comment by baggepinnen** [comment]
This should now work on master. A new release will be available within an hour.
```julia
julia> @show a = Particles(1000,Bernoulli(0.1))
a = Particles(1000, Bernoulli(0.1)) = 0.099 ± 0.3
Part1000(0.099 ± 0.299)

julia> @show a * 2
a * 2 = 0.198 ± 0.6
Part1000(0.198 ± 0.598)

julia> @show a * 2.05
a * 2.05 = 0.203 ± 0.61
Part1000(0.203 ± 0.613)
```
