### ISSUE TITLE
Stop overloading `norm(::Particle)`?

### ISSUE THREAD

**Issue by simeonschaub** [baggepinnen/MonteCarloMeasurements.jl#55]
The problem is that `norm` in Base works recursively, so I was quite surprised when `norm(::Vector{Particle}, 3)` returned just a float instead of a Particle.

**Comment by baggepinnen** [comment]
Ah, that was indeed a bit surprising. I guess we can provide a method for `norm(::Vector{Particle}, 3)` and that would solve the problem?

**Comment by baggepinnen** [comment]
I have been thinking about it and I think you are right, a Particle should behave like a scalar w.r.t `norm`. Should be fixed by https://github.com/simeonschaub/MonteCarloMeasurements.jl/pull/1

**Comment by baggepinnen** [comment]
closed by #56
