### ISSUE TITLE
Error with Arrayof Particles

### ISSUE THREAD

**Issue by arbenede** [baggepinnen/MonteCarloMeasurements.jl#65]
I want to pass to a custom function an Array of Particles, so I redefined one argument from Array{Float64,1} to  Array{Number,1}, however I am getting an error. With a non-Array argument everything works fine. Here is a MWE:

```
Y = [Particles(100, Normal(10+3i,2)) for i=1:3]

function g(x::Float64, Y::Array{Number,1})
    sum(Y) - x
end

g(1.0,Y)

MethodError: no method matching g(::Float64, ::Array{Particles{Float64,100},1})
Closest candidates are:
  g(::Float64, !Matched::Array{Number,1}) at In[21]:2

Stacktrace:
 [1] top-level scope at In[25]:1
```

What am I missing?

**Comment by baggepinnen** [comment]
You want
```julia
function g(x::Float64, Y::AbstractArray{<:Number,1})
```

**Comment by arbenede** [comment]
Thanks so much!

**Comment by baggepinnen** [comment]
By the way, there is almost never a reason to restrict your code this much
```julia
g(x::Float64
```
That will prevent you from using a lot of interesting types of input. Unless you need the restriction fo dispatch, you can leave the input arguments unrestricted, or, at the very least, restrict them as a little as possible, e.g.
```julia
g(x::Number
```
