### ISSUE TITLE
Question about register_primitive()

### ISSUE THREAD

**Issue by arbenede** [baggepinnen/MonteCarloMeasurements.jl#79]
I realized that I need to call

```
register_primitive(floor)
```
since floor() by default does not operate correctly on Particles. If I call it from the REPL then everything works fine. However when I call it from a function defined inside a module the code just hangs. I read in the help section:
```
  register_primitive(f, eval=eval)

  Register both single and multi-argument function so that it works with particles. If you want to
  register functions from within a module, you must pass the modules eval function.
```
however this is not 100% clear to me. An example would be great!

**Comment by baggepinnen** [comment]
This should work.
```julia
module MyMod
using MonteCarloMeasurements
register_primitive(floor, MyMod.eval)
end
```

**Comment by arbenede** [comment]
Yes, it works. Thanks!
